spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://db:3306/soccerFiveDB
        username: admin
        password: admin
